version: '3.9'

services:
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG:-latest}
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG:-main}
    container_name: open-webui
    depends_on:
      - ollama
    ports:
      - "3000:3000"  # ✅ Corrected Port Mapping
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # ✅ Ensures API key is loaded
      - ASSISTANT_ID=${ASSISTANT_ID}  # ✅ Ensures your assistant is linked
      - ENABLE_WEB_SEARCH=true  # ✅ Enables RAG-based search
    volumes:
      - open-webui:/app/backend/data
      - ./plugins:/app/plugins  # ✅ Ensures AI assistant & file parsing work
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
